# .github/workflows/autosync.yml

name: Merge upstream to main
on:
  schedule:
    - cron: '0 */12 * * *'  # A cada 12 horas

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'LeoTKBR'
          git config --global user.email '41605307+LeoTKBR@users.noreply.github.com'

          git pull --unshallow
          git remote add upstream https://github.com/opentibiabr/canary
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
